// Generated by jextract

package au.ikx.glcore;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef uint32_t (*pRENDERDOC_GetCapture)(uint32_t, char *, uint32_t *, uint64_t *)
 * }
 */
public class pRENDERDOC_GetCapture {

    pRENDERDOC_GetCapture() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(int idx, MemorySegment filename, MemorySegment pathlength, MemorySegment timestamp);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        RenderDoc.C_INT,
        RenderDoc.C_INT,
        RenderDoc.C_POINTER,
        RenderDoc.C_POINTER,
        RenderDoc.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = RenderDoc.upcallHandle(pRENDERDOC_GetCapture.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(pRENDERDOC_GetCapture.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,int idx, MemorySegment filename, MemorySegment pathlength, MemorySegment timestamp) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, idx, filename, pathlength, timestamp);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

