// Generated by jextract

package au.ikx.glcore;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef shaderc_include_result *(*shaderc_include_resolve_fn)(void *, const char *, int, const char *, size_t)
 * }
 */
public class shaderc_include_resolve_fn {

    shaderc_include_resolve_fn() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        MemorySegment apply(MemorySegment user_data, MemorySegment requested_source, int type, MemorySegment requesting_source, long include_depth);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        ShaderC.C_POINTER,
        ShaderC.C_POINTER,
        ShaderC.C_POINTER,
        ShaderC.C_INT,
        ShaderC.C_POINTER,
        ShaderC.C_LONG
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = ShaderC.upcallHandle(shaderc_include_resolve_fn.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(shaderc_include_resolve_fn.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment user_data, MemorySegment requested_source, int type, MemorySegment requesting_source, long include_depth) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, user_data, requested_source, type, requesting_source, include_depth);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

